# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abbd1c5b6ef69a15f91a29cb8506048efabebbca0c4637dd8b1f060edca439c285833e1b2015582a57a66c2dd46d937b8d41a9a381ee9c4051e22c0b54de51b3

test:
  secret_key_base: ef242b63c65ef87d0f065af6e3dbd10f87817aa647013f7ae2f28ea29c919f2e7969d2093158de8ae811e42133bda63559e3e1b51e0aeef3e2edf74de65e8f14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
